### Get all items
GET http://localhost:3333/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVGVuZ2l6IiwiaWF0IjoxNjUwODkzNzI5LCJleHAiOjE2NTA5ODAxMjl9.AVNW09XzR05MHM4GOydR477JxmUOLpkGgQL00s8MdWg

### Create a new to do item
POST http://localhost:3333/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVGVuZ2l6IiwiaWF0IjoxNjUwODkzNzI5LCJleHAiOjE2NTA5ODAxMjl9.AVNW09XzR05MHM4GOydR477JxmUOLpkGgQL00s8MdWg

{
    "description": "Eat khinkali"
}

### Update existing item
PATCH http://localhost:3333/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVGVuZ2l6IiwiaWF0IjoxNjUwODkzNzI5LCJleHAiOjE2NTA5ODAxMjl9.AVNW09XzR05MHM4GOydR477JxmUOLpkGgQL00s8MdWg


{
    "id": 9,
    "description": "stuff",
    "done": true
}

### Delete item
DELETE http://localhost:3333/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVGVuZ2l6IiwiaWF0IjoxNjUwODkzNzI5LCJleHAiOjE2NTA5ODAxMjl9.AVNW09XzR05MHM4GOydR477JxmUOLpkGgQL00s8MdWg

{
    "id": 9
}

### Sign up a new user
POST http://localhost:3333/api/auth/signup
Content-Type: application/json

{
    "username": "Nugzar",
    "email": "test@test1.com",
    "password": "hello_world"
}

### Sign in
POST http://localhost:3333/api/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "hello_world"
}

### Get currently signed in user id (test route)
GET http://localhost:3333/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVGVuZ2l6IiwiaWF0IjoxNjUwODkzNzI5LCJleHAiOjE2NTA5ODAxMjl9.AVNW09XzR05MHM4GOydR477JxmUOLpkGgQL00s8MdWg